import React, { useState } from 'react';
import { ToastContainer, toast } from 'react-toastify';
import { useNavigate } from 'react-router-dom';
import axios from 'axios';
import HomeInspection from './HomeInspection';
import { ActionButtons } from '../../components';
const HomeInfoStructure = () => {
  const [questionCount, setQuestionCount] = useState(1);
  const [check, setCheck] = useState(false);
  const [loading,setLoading]=useState(false);
  const [homeInspectionInfo, sethomeInspectionInfo] = useState({
    livingRoomFlooringType: '',
    livingRoomCeramicTileType: '',
    livingRoomStoneFlooringType: '',
    livingRoomWoodenFlooringType: '',
    livingRoomPvcFlooringType: '',
    livingRoomFlooringDefects: '',
    livingRoomFlooringRemarks: '',
    livingRoomWalls: '',
    livingRoomWallFinishing: '',
    livingRoomPaint: '',
    livingRoomWallTileCeramicType: '',
    livingRoomWallDefects: '',
    livingRoomWallRemarks: '',
    livingRoomCeiling: '',
    livingRoomCeilingPaint: '',
    livingRoomCeilingDefects: '',
    livingRoomCeilingRemarks: '',
    livingRoomDoorFrame: '',
    livingRoomDoorFrameDefects: '',
    livingRoomDoorDefects: '',
    livingRoomDoorHardware: '',
    livingRoomDoorHardwareDefects: '',
    livingRoomDoorRemarks: '',
    livingRoomWindowFrame: '',
    livingRoomWindowFrameDefects: '',
    livingRoomWindowHardware: '',
    livingRoomWindowHardwareDefects: '',
    livingRoomWindowShutter: '',
    livingRoomWindowShutterDefects: '',
    livingRoomWindowRemarks: '',
    livingRoomWallPanelDefects: '',
    livingRoomWallPanelRemarks: '',
    livingRoomPartition: '',
    livingRoomPartitionDefects: '',
    livingRoomPartitionRemarks: '',
    livingRoomElectricalWiring: '',
    livingRoomElectricalWiringDefects: '',
    livingRoomElectricalWiringRemarks: '',
    livingRoomElectricalPoints: '',
    livingRoomElectricalPointsDefects: '',
    livingRoomElectricalPointsRemarks: '',
    livingRoomCeilingLight: '',
    livingRoomCeilingLightDefects: '',
    livingRoomCeilingLightRemarks: '',
    livingRoomCeilingFanDefects: '',
    livingRoomAcDefects: '',
    livingRoomAcRemarks: '',
    livingRoomAlteration: '',
    livingRoomWallDemolition: '',
    livingRoomWallBuild: '',
    livingRoomBalconyFloorExtended: '',
    livingRoomBoxWindowSpaceUtilized: '',
    kitchenPlatform: '',
    kitchenPlatformDefects: '',
    kitchenPlatformRemarks: '',
    kitchenPlatformSink: '',
    kitchenPlatformSinkDefects: '',
    kitchenPlatformSinkRemarks: '',
    kitchenPlumbingDefects: '',
    kitchenPlumbingFixturesTap: '',
    kitchenPlumbingRemarks: '',
    kitchenFlooringType: '',
    kitchenCeramicTileType: '',
    kitchenStoneFlooringType: '',
    kitchenWoodenFlooringType: '',
    kitchenPvcFlooringType: '',
    kitchenFlooringDefects: '',
    kitchenFlooringRemarks: '',
    kitchenWalls: '',
    kitchenWallPlasterDefects: '',
    kitchenWallFinishing: '',
    kitchenPaint: '',
    kitchenWallTileCeramicType: '',
    kitchenWallDefects: '',
    kitchenWallRemarks: '',
    kitchenCeiling: '',
    kitchenCeilingPaint: '',
    kitchenCeilingDefects: '',
    kitchenCeilingRemarks: '',
    kitchenDoorFrame: '',
    kitchenDoorFrameDefects: '',
    kitchenDoorDefects: '',
    kitchenDoorHardware: '',
    kitchenDoorHardwareDefects: '',
    kitchenDoorRemarks: '',
    kitchenWindowFrame: '',
    kitchenWindowFrameDefects: '',
    kitchenWindowHardware: '',
    kitchenWindowHardwareDefects: '',
    kitchenWindowShutter: '',
    kitchenWindowShutterDefects: '',
    kitchenWindowRemarks: '',
    kitchenWallPanel: '',
    kitchenWallPanelDefects: '',
    kitchenWallPanelRemarks: '',
    kitchenWallPartition: '',
    kitchenWallPartitionDefects: '',
    kitchenWallPartitionRemarks: '',
    kitchenElectricalWiring: '',
    kitchenElectricalWiringDefects: '',
    kitchenElectricalWiringRemarks: '',
    kitchenElectricalPoints: '',
    kitchenElectricalPointsDefects: '',
    kitchenElectricalPointsRemarks: '',
    kitchenCeilingLight: '',
    kitchenCeilingLightDefects: '',
    kitchenCeilingLightRemarks: '',
    kitchenFanType: '',
    kitchenFanDefects: '',
    kitchenFanRemarks: '',
    kitchenChimney: '',
    kitchenChimneyDefects: '',
    kitchenChimneyRemarks: '',
    kitchenAlteration: '',
    kitchenWallDemolition: '',
    kitchenWallBuilt: '',
    kitchenBalconyFloorExtended: '',
    kitchenBoxWindowSpaceUtilized: '',
    kitchenBuiltPlatform: '',
    kitchenDemolishedPlatform: '',
    bathroomPlumbing: '',
    bathroomSanitaryFixtures: '',
    bathroomPlumbingFixtures: '',
    bathroomPlumbingFixturesType: '',
    bathroomPlumbingDefects: '',
    bathroomPlumbingRemarks: '',
    bathroomFlooringType: '',
    bathroomCeramicTileType: '',
    bathroomStoneFlooringType: '',
    bathroomWoodenFlooringType: '',
    bathroomPvcFlooringType: '',
    bathroomFlooringDefects: '',
    bathroomFlooringRemarks: '',
    bathroomWalls: '',
    bathroomWallDefects: '',
    bathroomWallFinishing: '',
    bathroomPaint: '',
    bathroomWallTileCeramicType: '',
    bathroomWallRemarks: '',
    bathroomCeiling: '',
    bathroomCeilingPaint: '',
    bathroomCeilingDefects: '',
    bathroomCeilingRemarks: '',
    bathroomDoorFrame: '',
    bathroomDoorFrameDefects: '',
    bathroomDoorFrameRemarks: '',
    bathroomDoorDefects: '',
    bathroomDoorHardware: '',
    bathroomDoorHardwareDefects: '',
    bathroomDoorRemarks: '',
    bathroomWindowFrame: '',
    bathroomWindowFrameDefects: '',
    bathroomWindowHardware: '',
    bathroomWindowHardwareDefects: '',
    bathroomWindowShutter: '',
    bathroomWindowShutterDefects: '',
    bathroomWindowRemarks: '',
    bathroomWallPanelDefects: '',
    bathroomWallPanelRemarks: '',
    bathroomWallPartition: '',
    bathroomWallPartitionDefects: '',
    bathroomWallPartitionRemarks: '',
    bathroomElectricalWiring: '',
    bathroomElectricalWiringDefects: '',
    bathroomElectricalWiringRemarks: '',
    bathroomElectricalPoints: '',
    bathroomElectricalPointsDefects: '',
    bathroomElectricalPointsRemarks: '',
    bathroomCeilingLight: '',
    bathroomCeilingLightDefects: '',
    bathroomCeilingLightRemarks: '',
    bathroomFan: '',
    bathroomFanDefects: '',
    bathroomFanRemarks: '',
    bathroomAlterations: '',
    bathroomWallDemolition: '',
    bathroomWallBuilt: '',
    bathroomBalconyFloorExtended: '',
    bathroomBoxWindowSpaceUtilized: '',
    bathroomBuiltPlatform: '',
    bathroomDemolishedPlatform: '',
    bedroomFlooringType: '',
    bedroomCeramicTileType: '',
    bedroomStoneFlooringType: '',
    bedroomWoodenFlooringType: '',
    bedroomPvcFlooringType: '',
    bedroomFlooringDefects: '',
    bedroomFlooringRemarks: '',
    bedroomWalls: '',
    bedroomWallPlasterDefects: '',
    bedroomWallFinishing: '',
    bedroomPaint: '',
    bedroomWallTileCeramicType: '',
    bedroomWallDefects: '',
    bedroomWallRemarks: '',
    bedroomCeiling: '',
    bedroomCeilingPaint: '',
    bedroomCeilingDefects: '',
    bedroomCeilingRemarks: '',
    bedroomDoorFrame: '',
    bedroomDoorFrameDefects: '',
    bedroomDoorFrameRemarks: '',
    bedroomDoorDefects: '',
    bedroomDoorHardware: '',
    bedroomDoorHardwareDefects: '',
    bedroomDoorRemarks: '',
    bedroomWindowFrame: '',
    bedroomWindowFrameDefects: '',
    bedroomWindowHardware: '',
    bedroomWindowHardwareDefects: '',
    bedroomWindowShutter: '',
    bedroomWindowShutterDefects: '',
    bedroomWindowRemarks: '',
    bedroomWallPanelDefects: '',
    bedroomWallPanelRemarks: '',
    bedroomElectricalWiring: '',
    bedroomElectricalWiringDefects: '',
    bedroomElectricalWiringRemarks: '',
    bedroomElectricalPoints: '',
    bedroomElectricalPointsDefects: '',
    bedroomElectricalPointsRemarks: '',
    bedroomCeilingLight: '',
    bedroomCeilingLightDefects: '',
    bedroomCeilingLightRemarks: '',
    bedroomFan: '',
    bedroomFanDefects: '',
    bedroomFanRemarks: '',
    bedroomAc: '',
    bedroomAcDefects: '',
    bedroomAcRemarks: '',
    bedroomAlterations: '',
    bedroomWallDemolition: '',
    bedroomWallBuilt: '',
    bedroomBalconyFloorExtended: '',
    bedroomBoxWindowSpaceUtilized: '',
  });
  console.log(homeInspectionInfo.bathroomWallRemarks);
  const successNotify = () =>
    toast.success('form filled Successfully', {
      position: 'bottom-center',
    });
  const failedNotify = () =>
    toast.error('something went wrong', {
      position: 'bottom-center',
    });
  const navigate = useNavigate();

  const Questions = [
    1,   2,   3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
    22,  23,  24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
    41,  42,  43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59,
    60,  61,  62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78,
    79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93, 94, 95, 96, 97,
    98,  99,  100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
    113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127,
    128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
    143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157,
    158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172,
    173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187,
    188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202,
    203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217,
    218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232,
    233, 234, 235,
  ];
  const mandatory = [
    1,   2,   3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
    22,  23,  24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
    41,  42,  43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59,
    60,  61,  62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78,
    79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93, 94, 95, 96, 97,
    98,  99,  100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
    113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127,
    128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
    143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157,
    158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172,
    173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187,
    188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202,
    203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217,
    218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232,
    233, 234, 235,
  ];
  //print 1 to 250 comma seperated values

  const Title = ['Living Room', 'Kitchen', 'Bathroom', 'Bedroom'];
  const onSubmit = e => {
    e.preventDefault();
    setLoading(true)
    const body = {
      // owner_name: 'owner_nameowner_nameowner_name',
      // property_type:'1',
      // society_name:'society_name',
      living_room_flooring_type: +homeInspectionInfo.livingRoomFlooringType,
      living_room_ceramic_tile_type:+homeInspectionInfo.livingRoomCeramicTileType,
      living_room_stone_flooring_type:+homeInspectionInfo.livingRoomStoneFlooringType,
      living_room_wooden_flooring_type:+homeInspectionInfo.livingRoomWoodenFlooringType,
      living_room_pvc_flooring_type:+homeInspectionInfo.livingRoomPvcFlooringType,
      living_room_flooring_defects:homeInspectionInfo.livingRoomFlooringDefects,
      living_room_flooring_remarks:homeInspectionInfo.livingRoomFlooringRemarks,
      living_room_walls: +homeInspectionInfo.livingRoomWalls,
      living_room_wall_finishing: +homeInspectionInfo.livingRoomWallFinishing,
      living_room_paint: +homeInspectionInfo.livingRoomPaint,
      living_room_wall_tile_ceramic_type:+homeInspectionInfo.livingRoomWallTileCeramicType,
      living_room_wall_defects: homeInspectionInfo.livingRoomWallDefects,
      living_room_wall_remarks: homeInspectionInfo.livingRoomWallRemarks,
      living_room_ceiling: +homeInspectionInfo.livingRoomCeiling,
      living_room_ceiling_paint: +homeInspectionInfo.livingRoomCeilingPaint,
      living_room_ceiling_defects: homeInspectionInfo.livingRoomCeilingDefects,
      living_room_ceiling_remarks: homeInspectionInfo.livingRoomCeilingRemarks,
      living_room_door_frame: +homeInspectionInfo.livingRoomDoorFrame,
      living_room_door_frame_defects:homeInspectionInfo.livingRoomDoorFrameDefects,
      living_room_door_defects: homeInspectionInfo.livingRoomDoorDefects,
      living_room_door_hardware: +homeInspectionInfo.livingRoomDoorHardware,
      living_room_door_hardware_defects:homeInspectionInfo.livingRoomDoorHardwareDefects,
      living_room_door_remarks:homeInspectionInfo.livingRoomDoorRemarks,
      living_room_window_frame: +homeInspectionInfo.livingRoomWindowFrame,
      living_room_window_frame_defects:homeInspectionInfo.livingRoomWindowFrameDefects,
      living_room_window_hardware: +homeInspectionInfo.livingRoomWindowHardware,
      living_room_window_hardware_defects:homeInspectionInfo.livingRoomWindowHardwareDefects,
      living_room_window_shutter: +homeInspectionInfo.livingRoomWindowShutter,
      living_room_window_shutter_defects:homeInspectionInfo.livingRoomWindowShutterDefects,
      living_room_window_remarks:homeInspectionInfo.livingRoomWindowRemarks,
      living_room_wall_panel_defects:homeInspectionInfo.livingRoomWallPanelDefects,
      living_room_wall_panel_remarks:homeInspectionInfo.livingRoomWallPanelRemarks,
      living_room_partition: +homeInspectionInfo.livingRoomPartition,
      living_room_partition_defects:homeInspectionInfo.livingRoomPartitionDefects,
      living_room_partition_remarks:homeInspectionInfo.livingRoomPartitionRemarks,
      living_room_electrical_wiring:+homeInspectionInfo.livingRoomElectricalWiring,
      living_room_electrical_wiring_defects:homeInspectionInfo.livingRoomElectricalWiringDefects,
      living_room_electrical_wiring_remarks:homeInspectionInfo.livingRoomElectricalWiringRemarks,
      living_room_electrical_points:+homeInspectionInfo.livingRoomElectricalPoints,
      living_room_electrical_points_defects:homeInspectionInfo.livingRoomElectricalPointsDefects,
      living_room_electrical_points_remarks:homeInspectionInfo.livingRoomElectricalPointsRemarks,
      living_room_ceiling_light: +homeInspectionInfo.livingRoomCeilingLight,
      living_room_ceiling_light_defects:homeInspectionInfo.livingRoomCeilingLightDefects,
      living_room_ceiling_light_remarks:homeInspectionInfo.livingRoomCeilingLightRemarks,
      living_room_ceiling_fan_defects:homeInspectionInfo.livingRoomCeilingFanDefects,
      living_room_ac_defects: homeInspectionInfo.livingRoomAcDefects,
      living_room_ac_remarks: homeInspectionInfo.livingRoomAcRemarks,
      living_room_alterations: homeInspectionInfo.livingRoomAlteration,
      living_room_wall_demolition: homeInspectionInfo.livingRoomWallDemolition,
      living_room_wall_built: homeInspectionInfo.livingRoomWallBuild,
      living_room_balcony_floor_extended: homeInspectionInfo.livingRoomBalconyFloorExtended,
      living_room_box_window_space_utilized: homeInspectionInfo.livingRoomBoxWindowSpaceUtilized,

      kitchen_platform: +homeInspectionInfo.kitchenPlatform,
      kitchen_platform_defects: homeInspectionInfo.kitchenPlatformDefects,
      kitchen_platform_remarks: homeInspectionInfo.kitchenPlatformRemarks,
      kitchen_platform_sink: +homeInspectionInfo.kitchenPlatformSink,
      kitchen_platform_sink_defects:homeInspectionInfo.kitchenPlatformSinkDefects,
      kitchen_platform_sink_remarks:homeInspectionInfo.kitchenPlatformSinkRemarks,
      kitchen_plumbing_defects: homeInspectionInfo.kitchenPlumbingDefects,
      kitchen_plumbing_fixtures_tap:+homeInspectionInfo.kitchenPlumbingFixturesTap,
      kitchen_plumbing_remarks:homeInspectionInfo.kitchenPlumbingRemarks,
      kitchen_flooring_type: +homeInspectionInfo.kitchenFlooringType,
      kitchen_ceramic_tile_type: +homeInspectionInfo.kitchenCeramicTileType,
      kitchen_stone_flooring_type: +homeInspectionInfo.kitchenStoneFlooringType,
      kitchen_wooden_flooring_type:+homeInspectionInfo.kitchenWoodenFlooringType,
      kitchen_pvc_flooring_type: +homeInspectionInfo.kitchenPvcFlooringType,
      kitchen_flooring_defects: homeInspectionInfo.kitchenFlooringDefects,
      kitchen_flooring_remarks: homeInspectionInfo.kitchenFlooringRemarks,
      kitchen_walls: +homeInspectionInfo.kitchenWalls,
      kitchen_wall_plaster_defects:homeInspectionInfo.kitchenWallPlasterDefects,
      kitchen_wall_finishing: +homeInspectionInfo.kitchenWallFinishing,
      kitchen_paint: +homeInspectionInfo.kitchenPaint,
      kitchen_wall_tile_ceramic_type:+homeInspectionInfo.kitchenWallTileCeramicType,
      kitchen_wall_defects: homeInspectionInfo.kitchenWallDefects,
      kitchen_wall_remarks: homeInspectionInfo.kitchenWallRemarks,
      kitchen_ceiling: +homeInspectionInfo.kitchenCeiling,
      kitchen_ceiling_paint: +homeInspectionInfo.kitchenCeilingPaint,
      kitchen_ceiling_defects: homeInspectionInfo.kitchenCeilingDefects,
      kitchen_ceiling_remarks: homeInspectionInfo.kitchenCeilingRemarks,
      kitchen_door_frame: +homeInspectionInfo.kitchenDoorFrame,
      kitchen_door_frame_defects: homeInspectionInfo.kitchenDoorFrameDefects,
      kitchen_door_defects: homeInspectionInfo.kitchenDoorDefects,
      kitchen_door_hardware: +homeInspectionInfo.kitchenDoorHardware,
      kitchen_door_hardware_defects:homeInspectionInfo.kitchenDoorHardwareDefects,
      kitchen_door_remarks:homeInspectionInfo.kitchenDoorRemarks,
      kitchen_window_frame: +homeInspectionInfo.kitchenWindowFrame,
      kitchen_window_frame_defects:homeInspectionInfo.kitchenWindowFrameDefects,
      kitchen_window_hardware: +homeInspectionInfo.kitchenWindowHardware,
      kitchen_window_hardware_defects:homeInspectionInfo.kitchenWindowHardwareDefects,
      kitchen_window_shutter: +homeInspectionInfo.kitchenWindowShutter,
      kitchen_window_shutter_defects:homeInspectionInfo.kitchenWindowShutterDefects,
      kitchen_window_remarks:homeInspectionInfo.kitchenWindowRemarks,
      kitchen_wall_panel: +homeInspectionInfo.kitchenWallPanel,
      kitchen_wall_panel_defects: homeInspectionInfo.kitchenWallPanelDefects,
      kitchen_wall_panel_remarks: homeInspectionInfo.kitchenWallPanelRemarks,
      kitchen_wall_partition: +homeInspectionInfo.kitchenWallPartition,
      kitchen_wall_partition_defects:homeInspectionInfo.kitchenWallPartitionDefects,
      kitchen_wall_partition_remarks:homeInspectionInfo.kitchenWallPartitionRemarks,
      kitchen_electrical_wiring: +homeInspectionInfo.kitchenElectricalWiring,
      kitchen_electrical_wiring_defects:homeInspectionInfo.kitchenElectricalWiringDefects,
      kitchen_electrical_wiring_remarks:homeInspectionInfo.kitchenElectricalWiringRemarks,
      kitchen_electrical_points: +homeInspectionInfo.kitchenElectricalPoints,
      kitchen_electrical_points_defects:homeInspectionInfo.kitchenElectricalPointsDefects,
      kitchen_electrical_points_remarks:homeInspectionInfo.kitchenElectricalPointsRemarks,
      kitchen_ceiling_light: +homeInspectionInfo.kitchenCeilingLight,
      kitchen_ceiling_light_defects:homeInspectionInfo.kitchenCeilingLightDefects,
      kitchen_ceiling_light_remarks:homeInspectionInfo.kitchenCeilingLightRemarks,
      kitchen_fan_type: +homeInspectionInfo.kitchenFanType,
      kitchen_fan_defects: homeInspectionInfo.kitchenFanDefects,
      kitchen_fan_remarks: homeInspectionInfo.kitchenFanRemarks,
      kitchen_chimney: +homeInspectionInfo.kitchenChimney,
      kitchen_chimney_defects: homeInspectionInfo.kitchenChimneyDefects,
      kitchen_chimney_remarks: homeInspectionInfo.kitchenChimneyRemarks,
      kitchen_alterations: homeInspectionInfo.kitchenAlteration ,
      kitchen_wall_demolition: homeInspectionInfo.kitchenWallDemolition ,
      kitchen_wall_built: homeInspectionInfo.kitchenWallBuilt ,
      kitchen_balcony_floor_extended: homeInspectionInfo.kitchenBalconyFloorExtended ,
      kitchen_box_window_space_utilized: homeInspectionInfo.kitchenBoxWindowSpaceUtilized ,
      kitchen_built_platform: homeInspectionInfo.kitchenBuiltPlatform ,
      kitchen_demolished_platform: homeInspectionInfo.kitchenDemolishedPlatform ,

      bathroom_plumbing: +homeInspectionInfo.bathroomPlumbing,
      bathroom_sanitary_fixtures: +homeInspectionInfo.bathroomSanitaryFixtures,
      bathroom_plumbing_fixtures: +homeInspectionInfo.bathroomPlumbingFixtures,
      bathroom_plumbing_fixtures_type:+homeInspectionInfo.bathroomPlumbingFixturesType,
      bathroom_plumbing_defects: homeInspectionInfo.bathroomPlumbingDefects,
      bathroom_plumbing_remarks: homeInspectionInfo.bathroomPlumbingRemarks,
      bathroom_flooring_type: +homeInspectionInfo.bathroomFlooringType,
      bathroom_ceramic_tile_type: +homeInspectionInfo.bathroomCeramicTileType,
      bathroom_stone_flooring_type:+homeInspectionInfo.bathroomStoneFlooringType,
      bathroom_wooden_flooring_type:+homeInspectionInfo.bathroomWoodenFlooringType,
      bathroom_pvc_flooring_type: +homeInspectionInfo.bathroomPvcFlooringType,
      bathroom_flooring_defects: homeInspectionInfo.bathroomFlooringDefects,
      bathroom_flooring_remarks: homeInspectionInfo.bathroomFlooringRemarks,
      bathroom_walls: +homeInspectionInfo.bathroomWalls,
      bathroom_wall_defects: homeInspectionInfo.bathroomWallDefects,
      bathroom_wall_finishing: +homeInspectionInfo.bathroomWallFinishing,
      bathroom_paint: +homeInspectionInfo.bathroomPaint,
      bathroom_wall_tile_ceramic_type:+homeInspectionInfo.bathroomWallTileCeramicType,
      bathroom_wall_remarks:+homeInspectionInfo.bathroomWallRemarks,
      bathroom_ceiling: +homeInspectionInfo.bathroomCeiling,
      bathroom_ceiling_paint: +homeInspectionInfo.bathroomCeilingPaint,
      bathroom_ceiling_defects: homeInspectionInfo.bathroomCeilingDefects,
      bathroom_ceiling_remarks: homeInspectionInfo.bathroomCeilingRemarks,
      bathroom_door_frame: +homeInspectionInfo.bathroomDoorFrame,
      bathroom_door_frame_defects: homeInspectionInfo.bathroomDoorFrameDefects,
      bathroom_door_frame_remarks: homeInspectionInfo.bathroomDoorFrameRemarks,
      bathroom_door_defects: homeInspectionInfo.bathroomDoorDefects,
      bathroom_door_hardware: +homeInspectionInfo.bathroomDoorHardware,
      bathroom_door_hardware_defects:homeInspectionInfo.bathroomDoorHardwareDefects,
      bathroom_door_remarks:homeInspectionInfo.bathroomDoorRemarks,
      bathroom_window_frame: +homeInspectionInfo.bathroomWindowFrame,
      bathroom_window_frame_defects:homeInspectionInfo.bathroomWindowFrameDefects,
      bathroom_window_hardware: +homeInspectionInfo.bathroomWindowHardware,
      bathroom_window_hardware_defects:homeInspectionInfo.bathroomWindowHardwareDefects,
      bathroom_window_shutter: +homeInspectionInfo.bathroomWindowShutter,
      bathroom_window_shutter_defects:homeInspectionInfo.bathroomWindowShutterDefects,
      bathroom_window_remarks:homeInspectionInfo.bathroomWindowRemarks,
      bathroom_wall_panel_defects: homeInspectionInfo.bathroomWallPanelDefects,
      bathroom_wall_panel_remarks: homeInspectionInfo.bathroomWallPanelRemarks,
      bathroom_wall_partition: +homeInspectionInfo.bathroomWallPartition,
      bathroom_wall_partition_defects:homeInspectionInfo.bathroomWallPartitionDefects,
      bathroom_wall_partition_remarks:homeInspectionInfo.bathroomWallPartitionRemarks,
      bathroom_electrical_wiring: +homeInspectionInfo.bathroomElectricalWiring,
      bathroom_electrical_wiring_defects:homeInspectionInfo.bathroomElectricalWiringDefects,
      bathroom_electrical_wiring_remarks:homeInspectionInfo.bathroomElectricalWiringRemarks,
      bathroom_electrical_points: +homeInspectionInfo.bathroomElectricalPoints,
      bathroom_electrical_points_defects:homeInspectionInfo.bathroomElectricalPointsDefects,
      bathroom_electrical_points_remarks:homeInspectionInfo.bathroomElectricalPointsRemarks,
      bathroom_ceiling_light: +homeInspectionInfo.bathroomCeilingLight,
      bathroom_ceiling_light_defects:homeInspectionInfo.bathroomCeilingLightDefects,
      bathroom_ceiling_light_remarks:homeInspectionInfo.bathroomCeilingLightRemarks,
      bathroom_fan: +homeInspectionInfo.bathroomFan,
      bathroom_fan_defects: homeInspectionInfo.bathroomFanDefects,
      bathroom_fan_remarks: homeInspectionInfo.bathroomFanRemarks,
      bathroom_alterations: homeInspectionInfo.bathroomAlterations ,
      bathroom_wall_demolition: homeInspectionInfo.bathroomWallDemolition ,
      bathroom_wall_built: homeInspectionInfo.bathroomWallBuilt ,
      bathroom_balcony_floor_extended: homeInspectionInfo.bathroomBalconyFloorExtended ,
      bathroom_box_window_space_utilized: homeInspectionInfo.bathroomBoxWindowSpaceUtilized ,
      bathroom_built_platform: homeInspectionInfo.bathroomBuiltPlatform ,
      bathroom_demolished_platform: homeInspectionInfo.bathroomDemolishedPlatform ,

      bedroom_flooring_type: +homeInspectionInfo.bedroomFlooringType,
      bedroom_ceramic_tile_type: +homeInspectionInfo.bedroomCeramicTileType,
      bedroom_stone_flooring_type: +homeInspectionInfo.bedroomStoneFlooringType,
      bedroom_wooden_flooring_type:+homeInspectionInfo.bedroomWoodenFlooringType,
      bedroom_pvc_flooring_type: +homeInspectionInfo.bedroomPvcFlooringType,
      bedroom_flooring_defects: homeInspectionInfo.bedroomFlooringDefects,
      bedroom_flooring_remarks: homeInspectionInfo.bedroomFlooringRemarks,
      bedroom_walls: +homeInspectionInfo.bedroomWalls,
      bedroom_wall_plaster_defects: homeInspectionInfo.bedroomWallPlasterDefects,
      bedroom_wall_finishing: +homeInspectionInfo.bedroomWallFinishing,
      bedroom_paint: +homeInspectionInfo.bedroomPaint,
      bedroom_wall_tile_ceramic_type:+homeInspectionInfo.bedroomWallTileCeramicType,
      bedroom_wall_defects: homeInspectionInfo.bedroomWallDefects,
      bedroom_wall_remarks: homeInspectionInfo.bedroomWallRemarks,
      bedroom_ceiling: +homeInspectionInfo.bedroomCeiling,
      bedroom_ceiling_paint: +homeInspectionInfo.bedroomCeilingPaint,
      bedroom_ceiling_defects: homeInspectionInfo.bedroomCeilingDefects,
      bedroom_ceiling_remarks: homeInspectionInfo.bedroomCeilingRemarks,
      bedroom_door_frame: +homeInspectionInfo.bedroomDoorFrame,
      bedroom_door_frame_defects: homeInspectionInfo.bedroomDoorFrameDefects,
      bedroom_door_frame_remarks: homeInspectionInfo.bedroomDoorFrameRemarks,
      bedroom_door_defects: homeInspectionInfo.bedroomDoorDefects,
      bedroom_door_hardware: +homeInspectionInfo.bedroomDoorHardware,
      bedroom_door_hardware_defects:homeInspectionInfo.bedroomDoorHardwareDefects,
      bedroom_door_remarks:homeInspectionInfo.bedroomDoorRemarks,
      bedroom_window_frame: +homeInspectionInfo.bedroomWindowFrame,
      bedroom_window_frame_defects:homeInspectionInfo.bedroomWindowFrameDefects,
      bedroom_window_hardware: +homeInspectionInfo.bedroomWindowHardware,
      bedroom_window_hardware_defects:homeInspectionInfo.bedroomWindowHardwareDefects,
      bedroom_window_shutter: +homeInspectionInfo.bedroomWindowShutter,
      bedroom_window_shutter_defects:homeInspectionInfo.bedroomWindowShutterDefects,
      bedroom_window_remarks:homeInspectionInfo.bedroomWindowRemarks,
      bedroom_wall_panel_defects: homeInspectionInfo.bedroomWallPanelDefects,
      bedroom_wall_panel_remarks: homeInspectionInfo.bedroomWallPanelRemarks,
      bedroom_electrical_wiring: +homeInspectionInfo.bedroomElectricalWiring,
      bedroom_electrical_wiring_defects:homeInspectionInfo.bedroomElectricalWiringDefects,
      bedroom_electrical_wiring_remarks:homeInspectionInfo.bedroomElectricalWiringRemarks,
      bedroom_electrical_points: +homeInspectionInfo.bedroomElectricalPoints,
      bedroom_electrical_points_defects:homeInspectionInfo.bedroomElectricalPointsDefects,
      bedroom_electrical_points_remarks:homeInspectionInfo.bedroomElectricalPointsRemarks,
      bedroom_ceiling_light: +homeInspectionInfo.bedroomCeilingLight,
      bedroom_ceiling_light_defects:homeInspectionInfo.bedroomCeilingLightDefects,
      bedroom_ceiling_light_remarks:homeInspectionInfo.bedroomCeilingLightRemarks,
      bedroom_fan: +homeInspectionInfo.bedroomFan,
      bedroom_fan_defects: homeInspectionInfo.bedroomFanDefects,
      bedroom_fan_remarks: homeInspectionInfo.bedroomFanRemarks,
      bedroom_ac: +homeInspectionInfo.bedroomAc,
      bedroom_ac_defects: homeInspectionInfo.bedroomAcDefects,
      bedroom_ac_remarks: homeInspectionInfo.bedroomAcRemarks ,
      bedroom_alterations: homeInspectionInfo.bedroomAlterations ,
      bedroom_wall_demolition: homeInspectionInfo.bedroomWallDemolition ,
      bedroom_wall_built: homeInspectionInfo.bedroomWallBuilt ,
      bedroom_balcony_floor_extended: homeInspectionInfo.bedroomBalconyFloorExtended ,
      bedroom_box_window_space_utilized: homeInspectionInfo.bedroomBoxWindowSpaceUtilized ,
    };
    // console.log(homeInspectionInfo);
    const data = {
      Accept: 'application/json',
      'Content-type': 'application/json',
      Authorization: `Bearer ${localStorage.getItem('token')}`,
    };

    axios
      .put(
        `api/tasks/${localStorage.getItem('task_id')}/home-inspection/`,
        body,
        {
          headers: data,
        },
      )
      .then(res => {
        successNotify();
        navigate('/todays-task', { replace: true });
        const status = { status: "C" };
        axios.patch(`api/tasks/${localStorage.getItem("task_id")}/`, status, {
          headers: {
            Authorization: `Bearer ${localStorage.getItem("token")}`,
          },
        });
      })
      .catch(err => {
        failedNotify();
        setLoading(false)
      });
  };

  let keysArr = Object.keys(homeInspectionInfo);
 
  console.log(keysArr, "keysArr >>>>",questionCount,"ques",homeInspectionInfo[keysArr[questionCount-1]]);
  return (
    <div>
      <ToastContainer autoClose={1500} />
      <div className='p-3 text-center mt-10 '>
        <h2 className='text-sky-600 text-2xl font-bold'>Home Inspection</h2>
        <div className='text-left'>
          <div className='progress'></div>
          <div className='flex px-5 mt-10 justify-between'>
            <div className='text-lg font-bold text-sky-500  '>
              {' '}
              {questionCount <= 52
                ? Title[0]
                : questionCount <= 120
                ? Title[1]
                : questionCount <= 181
                ? Title[2]
                : Title[3]}
            </div>
            <div className='font-normal  '>
              Total Questions: {Questions.length}
            </div>
          </div>
          <div className='form-container border-4 border-solid shadow-2xl shadow-indigo-500/40 rounded-2xl border-zinc-400   py-10 px-5 '>
            <div className='main-body  '>
              <HomeInspection
                questionCount={questionCount}
                homeInspectionInfo={homeInspectionInfo}
                sethomeInspectionInfo={sethomeInspectionInfo}
                check={check}
              />
            </div>
          </div>
          <ActionButtons
            setCheck={setCheck}
            setQuestionCount={setQuestionCount}
            onSubmit={onSubmit}
            mandatory={mandatory}
            questionCount={questionCount}
            loading={loading}
            objName={homeInspectionInfo}
            finishNo={235}
          />
        </div>
      </div>
    </div>
  );
};

export default HomeInfoStructure;
